// src/modules/resource-explorer/common/component/card.svelte
<script lang="ts">
    import { ClassBuilder } from 'smelte/src/utils/classes.js';

    const defaultCardClasses =
        'w-full relative hover:shadow-card bg-white rounded-3xl active:shadow-none active:opacity-70';

    const cardClassesBuilder = new ClassBuilder(defaultCardClasses);

    export let classes = 'overflow-hidden';

    $: cardComputedClass = cardClassesBuilder.flush().add(classes).get();
</script>

<div class={cardComputedClass} on:click>
    <slot />
</div>

// packages/module/resource-explorer/common/component/card.vue
<template>
    <div :class="$style.card">
        <slot />
    </div>
</template>

<style module>
.card {
    position: relative;
    width: 100%;
    background: #fff;
    border-radius: 16px;
    overflow: hidden;
}
.card:hover {
    box-shadow: 1px 4px 6px 0 rgba(0, 0, 0, 0.1);
}
.card:active {
    opacity: .7;
}
</style>
