// packages/module/app-user/view/login.vue
<script lang="ts" setup>
import { ref } from 'vue';
import { Input, Button } from 'cosmic-vue';
import { service, inject } from '@cosmic/core/browser';


const rootRouterService = inject<service.RouterService>(service.TOKENS.Router);
const userService = inject<service.UserService>(service.TOKENS.User);

const username = ref('');
const password = ref('');
const redirect = JSON.parse(localStorage.getItem('redirect') || '{"path":"/"}');
localStorage.removeItem('redirect');


function onLogin() {
    userService.login({
        username: username.value, password: password.value,
    }).then(() => {
        rootRouterService.replace(redirect);
    });
}
</script>

<template>
    <Layout>
        <div class="w-full h-full relative" :class="$style.page">
            <div class="flex flex-col items-center box-border" :class="$style.login">
                <div :class="$style.logo">
                    <img class="w-full h-full" src="https://fe-dev.bj.bcebos.com/login-logo.png" alt="logo">
                </div>
                <div class="text-2xl font-medium" :class="$style.title">欢迎登陆无极</div>
                <Input v-model:value="username" placeholder="请输入账号/邮箱" class="w-full mt-30 mb-12" :class="$style.input" />
                <Input v-model:value="password" type="password" placeholder="请输入密码" class="w-full mb-24" :class="$style.input" />
                <Button type="primary" class="w-full" size="lg" @click="onLogin">登陆</Button>
            </div>
        </div>
    </Layout>
</template>

<style module>
.page {
    background: #f3f3f3;
}
.login {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 384px;
    height: 376px;
    padding: 45px 70px 60px;
    background: var(--color-white);
    border-radius: 8px;
}
.logo {
    margin-top: 18px;
    width: 48px;
    height: 48px;
}
.title {
    margin-top: 18px;
    height: 28px;
    line-height: 28px;
}
.input {
    border: 1px solid #e0e0e0;
}
</style>

// src/modules/resource-explorer/auth/login.svelte
<script lang="ts">
  import { Layout, Button } from '@cosmic/core/components';
  import { login } from '../auth/user';
  import { push } from 'svelte-spa-router';
  import { urlFor, ROUTES } from '../routes';
  

  let username = '';
  let password = '';

  function onLogin () {
    login({ username, password }).then(() => {
      push(urlFor(ROUTES.INDEX))
    });
  }
</script>

<Layout>
  <div class="w-full h-full bg-gray-100">
    <div class="absolute flex left-1/2 top-1/2 w-890 h-418 rounded-4xl overflow-hidden transform -translate-x-1/2 -translate-y-1/2">
      <div class="h-full w-520">
        <img class="h-full w-full" src="https://fe-dev.bj.bcebos.com/login.png" alt="">
      </div>
      <div class="h-full w-370 box-border px-40 flex flex-col justify-center bg-white">
        <div class="text-h3 font-semibold">
          账号登陆
        </div>
        <div class="text-h4 mt-40 mb-20">
          <label for="username">账号*</label>
          <input
            bind:value="{username}"
            class="ml-10 box-border p-10 w-240 h-36 rounded border-gray-400 border-solid border opacity-60"
            name="username" id="username" type="text" placeholder="请输入账号/邮箱"
          >
        </div>
        <div class="text-h4 mb-30">
          <label for="password">密码*</label>
          <input
            bind:value="{password}"
            class="ml-10 box-border p-10 w-240 h-36 rounded border-gray-400 border-solid border opacity-60"
            name="password" id="password" type="password" placeholder="请输入密码"
          >
        </div>
        <div class="text-right">
          <Button type="primary" classes="rounded-xl" on:click="{onLogin}">登陆</Button>
        </div>
      </div>
    </div>
  </div>
</Layout>
