// packages/module/sheikah/design/component/atom/micro-card.vue
<script lang="ts" setup>
    // import { Menu } from 'cosmic-vue';
    import Card from '../../../common/component/card.vue';
    import Preview from './cell/color.vue';

    // TODO delete it after gql modle upgrade
    interface Color {
        value: {
            day: string;
            night: string;
            dark: string;
        },
        title?: string;
        meta?: string;
        refCount: number;
    }

    withDefaults(defineProps<Color>(), {
        value: () => {
            return { day: 'none', night: 'none', dark: 'none'};
        },
        title: '',
        meta: '',
    });

</script>

<template>
    <Card :class="$style['atom-micro-card']">
        <div :class="$style['atom-preview']">
            <Preview v-bind="value" />
        </div>
        <div :class="$style['atom-info']">
            <div :class="$style['atom-title']">
                {{ title }}
            </div>
            <div class="mt-6">
                {{ meta }}
            </div>
        </div>

        <div
            :class="$style['atom-extra']"
            class="flex items-center"
        >
            <div :class="$style['atom-link-icon']">
                <i-cosmic-lock style="font-size: 12px" />
            </div>
            <span :class="$style['atom-link-num']">{{ refCount }}</span>
        </div>
    </Card>
</template>

<style module>
.atom-micro-card {
    display: flex;
    position: relative;
    padding: 14px;
    font-size: var(--font-sm);
    color: #1f1f1f;
    border-radius: 9px;
}
.atom-preview {
    flex: none;
    width: 72px;
    height: 72px;
    margin-right: 12px;
    border-radius: 8px;
}
.atom-info {
    height: 72px;
    padding-right: 10px;
    flex: auto;
    color: #858585
}
.atom-title {
    color: #1f1f1f;
}
.atom-extra {
    position: absolute;
    bottom: 18px;
    right: 17px;
    height: 26px;
}
.atom-link-num {
    display: inline-block;
    max-width: 24px;
    vertical-align: middle;
    opacity: .7;
    white-space: nowrap;
}
.atom-link-icon {
    margin-right: 10px;
    width: 12px;
    height: 12px;
    font-size: var(--font-sm);
}
</style>

// src/modules/resource-explorer/design/component/atom/micro-card.svelte
<script lang="ts">
    import { Icon, Dropdown } from '@cosmic/core/components';
    import Card from '../../../common/component/card.svelte';

    const items = [
        {
            value: 1,
            text: '编辑',
        },
        {
            value: 2,
            text: '删除',
        },
    ];

    export let classes = '';
    export let color = 'none';
</script>

<Card classes="relative h-106 flex p-14 {classes}">
    <div class="w-78 h-78 mr-12 flex-none rounded-xl" style="background: {color}" />
    <div class="flex flex-auto pr-10">
        <div class="flex flex-col justify-between py-10 text-gray-700 text-base">
            <div class="text-black">一级标题</div>
            <div>FC001</div>
            <div>三图模版</div>
        </div>
    </div>

    <div class="absolute flex items-center bottom-14 right-14 h-26 text-base text-black">
        <div class="mr-10">
            <Icon classes="inline-block mr-10 align-middle">swap_horiz</Icon>
            <span class="inline-block align-middle opacity-70 max-w-sm whitespace-nowrap">3</span>
        </div>
        <div>
            <Icon classes="inline-block mr-10 align-middle">link</Icon>
            <span class="inline-block align-middle opacity-70 max-w-sm whitespace-nowrap">3</span>
        </div>
    </div>
    <Dropdown classes="absolute top-14 right-14" {items} />
</Card>
