// packages/module/sheikah/common/component/dialog.vue
<script lang="ts" setup>
interface DialogOptions {
    open: boolean;
    width: string | number;
    height: string | number;
}

withDefaults(defineProps<DialogOptions>(), {
    open: false,
    width: 'auto',
    height: 'auto',
});

</script>

<template>
    <div :class="$style.dialog" style="width: {width}; height: {height}" :style="{ display: open ? 'block' : 'none'}">
        <div class="text-xl font-bold">
            <slot name="title" />
        </div>
        <div class="my-20">
            <slot />
        </div>
        <div class="w-full flex justify-center items-center">
            <slot name="actions" />
        </div>
    </div>
</template>

<style module>
.dialog {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%);
    box-sizing: border-box;
    padding: 24px;
    background: #fff;
    color: #1f1f1f;
    z-index: 50;
    border-radius: 15px;
    font-weight: var(--font-bold);
    box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.5);
}
</style>

// src/core/components/dialog/dialog.svelte
<script>
  import { scale } from 'svelte/transition';
  import { quadIn } from 'svelte/easing';
  import { Scrim } from 'smelte/src/components/Util/index.js';
  import { ClassBuilder } from 'smelte/src/utils/classes.js';

  const classesDefault = 'box-border text-black items-center z-50 rounded-4xl bg-white p-24 shadow-dialog';
  const titleClassesDefault = 'text-h2 font-bold pb-16';
  const actionsClassesDefault = 'w-full';

  export let value;
  export let classes = '';
  export let titleClasses = '';
  export let actionsClasses = '';
  export let opacity = 0.5;
  export let persistent = false;
  export let width = 'auto';
  export let height = 'auto';

  export let transitionProps = { duration: 150, easing: quadIn, delay: 150 };

  const cb = new ClassBuilder(classesDefault);
  const tcb = new ClassBuilder(titleClassesDefault);
  const acb = new ClassBuilder(actionsClassesDefault);

  $: c = cb.flush().add(classes, true, classesDefault).get();

  $: t = tcb.flush().add(titleClasses, true, actionsClassesDefault).get();

  $: a = acb.flush().add(actionsClasses, true, actionsClassesDefault).get();
</script>

<div class="fixed w-full h-full top-0 left-0 z-30" class:hidden={!value}>
  <Scrim opacity="{opacity}" on:click="{() => !persistent && (value = false)}" />
  <div class="h-full w-full absolute flex items-center justify-center">
    <div in:scale="{transitionProps}" class="{c}" style="width: {width}; height: {height}">
      <div class="{t}">
        <slot name="title" />
      </div>
      <slot />
      <div class="{a}">
        <slot name="actions" />
      </div>
    </div>
  </div>
</div>
