// packages/module/sheikah/common/component/header.vue
<script lang="ts" setup>
    import { Layout } from 'cosmic-vue';

    const { Header } = Layout;
</script>

<template>
    <Header>
        <div class="header">
            <img
                class="logo"
                src="https://fe-dev.bj.bcebos.com/cosmic/%E6%97%A0%E6%9E%81LOGO.png"
                alt="logo"
            >
            <span>无极设计中台</span>
        </div>
    </Header>
</template>

<style module>
.header {
    display: flex;
    align-items: center;
    font-size: 12px;
    color: #1f1f1f;
}
.logo {
    width: 24px;
    height: 20px;
    margin-right: 7px;
}
</style>

// src/modules/resource-explorer/common/component/header.svelte
<script lang="ts">
    import { Layout } from '@cosmic/core/components';

    const { Header } = Layout;
</script>

<Header>
    <div class="flex items-center text-base text-black">
        <img class="w-24 h-20 mr-7" src="https://fe-dev.bj.bcebos.com/cosmic/%E6%97%A0%E6%9E%81LOGO.png" alt="logo" />
        <span>无极设计中台</span>
    </div>
</Header>
