// packages/module/sheikah/project/component/file-card.vue
<script lang="ts" setup>
import Card from '../../common/component/card.vue';

export interface ProjectProps {
    img: string;
    title: string;
    desc: string;
}

withDefaults(defineProps<ProjectProps>(), {
    img: 'https://fe-dev.bj.bcebos.com/file-card.png',
    title: '',
    desc: '编辑于 昨天',
});

</script>

<template>
    <Card :class="$style['card-container']">
        <div :class="$style['card-content']">
            <div style="flex: auto;">
                <img
                    :src="img"
                    alt=""
                >
            </div>
            <div :class="$style['card-content-info']">
                <div :class="$style['card-title']">
                    {{ title }}
                </div>
                <div :class="$style['card-date']">
                    {{ desc }}
                </div>
            </div>
        </div>
    </Card>
</template>

<style module>
.card-container {
    position: relative;
    overflow: hidden;
    height: 0;
    padding-bottom: 75%;
    border-radius: 8px;
}
.card-content {
    position: absolute;
    display: flex;
    flex-direction: column;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
.card-content-info {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: flex-start;
    height: 78px;
    padding: 0 14px;
    background: #fff;
}
.card-title {
    font: 16px;
    height: 16px;
}
.card-date {
    margin-top: 10px;
    font-size: 12px;
}
</style>

// src/modules/resource-explorer/project/component/file-card.svelte
<script lang="ts">
  import Card from '../../common/component/card.svelte';

  export const project = {
    img: '',
    title: '标题',
    desc: '描述'
  };
</script>

<Card classes="relative h-0 pb-3/4 rounded-xl overflow-hidden">
  <div class="w-full h-full absolute flex flex-col top-0 left-0">
    <div class="flex-auto">
      <img src="{project.img || `https://fe-dev.bj.bcebos.com/file-card.png`}" alt="" />
    </div>
    <div class="h-78 px-14 flex flex-col items-start justify-center  bg-white">
      <div class="text-h3 h-16 items-center">{project.title}</div>
      <div class="mt-10 text-base flex-a items-center">{project.desc || '编辑于 昨天'}</div>
    </div>
  </div>
</Card>
